Layer _name
ansys/pyedb pull request #246
Opened 2024-03-07 15:13 UTC by gkorompi

layer_name bug fix. Please compare previous and new code.

2024-03-07 15:30 UTC, svandenb-dev commented on tests/legacy/system/test_edb_modeler.py
> +        edbapp.stackup.add_layer("d3", layer_type="dielectric", thickness="13mil", material="FR4_epoxy")
You are missing the assert in your test

2024-03-07 17:19 UTC, SMoraisAnsys requested changes
Thanks for the PR, I would advise to rework the test in the PR to correct the lack of assert(s) and make them simpler. I have the feeling that the created data does not need to be so complex. Moreover, since you are adding something to the test class, it might be wise to leverage what is already performed in other tests. 

Note: I'm clearly in favor of having tests that can run in standalone (like you did) but it seems that opening and closing EDB a lot of times can lead to unexpected failures.

2024-03-07 17:19 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/edb_data/primitives_data.py
> +                        dupli_poly.prim_obj.AddVoid(dupli_void.prim_obj)
```suggestion
        for layer in layers:
            if layer in self._pedb.stackup.layers:
                dupli_poly = self._app.edb_api.cell.primitive.polygon.create(
                    self._app.active_layout, layer, self.net, self.polygon_data.edb_api
                )
                if dupli_poly:
                    for void in self.voids:
                        dupli_void = self._app.edb_api.cell.primitive.polygon.create(
                            self._app.active_layout, layer, self.net, void.polygon_data.edb_api
                        )
                        dupli_poly.prim_obj.AddVoid(dupli_void.prim_obj)
```

2024-03-07 17:19 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/edb_data/primitives_data.py
> +        layer: list
```suggestion
        layers: list
```

2024-03-07 17:19 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/edb_data/primitives_data.py
> -    @layer_name.setter
You just removed the fact that property decorates with `.setter`. You should put back the removed `@layer_name.setter`

2024-03-07 17:19 UTC, SMoraisAnsys commented on tests/legacy/system/test_edb_modeler.py
> +        if edbapp.modeler.primitives_by_layer["bot_gnd"]: print("True")
Please use assertions here instead of print

2024-03-07 17:19 UTC, SMoraisAnsys commented on tests/legacy/system/test_edb_modeler.py
> +        r1.layer_name
As @svandenb-dev said, you are missing assertions here.

2024-03-08 15:47 UTC, SMoraisAnsys reviewed
LGTM

Please, next time, commit the suggestion as proposed when possible. It eases the fact of reviewing again.

2024-03-13 10:13 UTC, svandenb-dev submitted a review, later dismissed
LGTM

2024-03-14 07:45 UTC, SMoraisAnsys approved these changes
LGTM

2024-03-22 14:50 UTC, closed without merging