354 setup
ansys/pyedb pull request #355
Opened 2024-04-11 08:56 UTC by gkorompi

2024-04-11 15:15 UTC, SMoraisAnsys commented on tests/legacy/system/test_edb.py
> +        assert setup2 == None
```suggestion
        assert not edbapp.create_hfss_setup("setup1")
```

2024-04-11 15:16 UTC, SMoraisAnsys commented on tests/legacy/system/test_edb.py
> +        assert setup2 == None
I do agree with your point (and propose another change though)

2024-04-11 15:17 UTC, SMoraisAnsys requested changes
Please fix the return value as pointed by @ring630 and either pick his proposition or mine for the test

2024-04-12 09:35 UTC, ring630 approved these changes
LGTM

2024-04-12 10:31 UTC, SMoraisAnsys approved these changes

2024-04-12 10:31 UTC, merged