Fix: package def
ansys/pyedb pull request #362
Opened 2024-04-12 14:19 UTC by ring630

2024-04-13 05:56 UTC, ring630 commented
@SMoraisAnsys pycharm doesn't allow ":" in PR name. Is it possible to change the naming rule from "FIX:" to "FIX-"?

2024-04-13 08:31 UTC, SMoraisAnsys commented
> @SMoraisAnsys pycharm doesn't allow ":" in PR name. Is it possible to change the naming rule from "FIX:" to "FIX-"?

Do you mean branch name ? It shouldn't be a problem to use ":" in a PR title. If that's the case, i assume there is a way to make it work. Using "-" instead is not standard commit style and is quite awkward IMO

2024-04-13 08:37 UTC, SMoraisAnsys requested changes
On top of the minor comment I left, could you add the copyright on each new files ? Some do not have it.

2024-04-13 08:37 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/geometry/point_data.py
> +            self._edb_object = self._pedb.edb_api.geometry.point_data(
Won't this fail if `x` or `y` is `None`?

2024-04-13 08:37 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/geometry/polygon_data.py
> +        **args,
Could you use `kwargs` instead here ? `args` is more commonly used like `*args`

2024-04-15 08:29 UTC, SMoraisAnsys approved these changes
LGTM, thanks for taking into account previous review comments !

2024-04-15 11:35 UTC, merged