FEATURE: get_plot_data()
ansys/pyedb pull request #367
Opened 2024-04-15 09:50 UTC by gkorompi

2024-04-15 14:05 UTC, SMoraisAnsys requested changes
@svandenb-dev @ring630 Can one of you confirm the changes as it will modify the default behavior of the method.

2024-04-15 14:05 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/nets.py
> +        nets=None,
Could you update the description to:
- add `optional` to `nets` types (this should already have been performed)
- specify that, by default, all nets will be considered

2024-04-15 14:29 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/nets.py
> +            Name of the net or list of nets to plot. If `None` all nets will be plotted. (default)
```suggestion
            Name of the net or list of nets to plot. If `None` (default value) all nets will be plotted.
```

2024-04-16 06:12 UTC, ring630 commented
> @svandenb-dev @ring630 Can one of you confirm the changes as it will modify the default behavior of the method.

@SMoraisAnsys it is a bug. When nets==None, all nets are plotted. However, nets is a mandatory input, which makes no sense.

2024-04-16 06:13 UTC, ring630 approved these changes
LGTM

2024-04-16 07:25 UTC, SMoraisAnsys approved these changes

2024-04-16 07:25 UTC, merged