FIX: via mesh
ansys/pyedb pull request #500
Opened 2024-05-22 08:40 UTC by gkorompi

2024-05-22 10:46 UTC, ring630 commented
Customer can still run pyedb on older aedt version. Why do you want to remove the version check?

2024-05-22 11:37 UTC, gkorompi commented
@ring630 please check comment here: 
https://github.com/ansys/pyedb/issues/352

2024-05-22 13:59 UTC, ring630 requested changes
via_mesh_plating should not be allowed in 23.2 and older version

2024-05-23 05:54 UTC, gkorompi commented
It will not crash, it depends solely on the AEDT version that is used to open the design. If you define the variable in 23.2 edb and you launch it with 24.2 aedt, then the option will be there. Also, the dataset is not updated until saved, so it makes no sense to check it as soon as it is not updated! @svandenb-dev  what's your opinion?

2024-05-23 09:51 UTC, SMoraisAnsys commented on src/pyedb/dotnet/edb_core/edb_data/hfss_simulation_setup_data.py
> +        self._parent._pedb.logger.warning("Property only supported on Ansys release 2024R1 and later")
Just so you know, this log warning will never be triggered as a return if performed just before.

2024-05-27 11:18 UTC, closed without merging

2024-05-27 11:21 UTC, ring630 commented
@gkorompi I am not convinced by this PR. I closed it for now.

2024-05-27 11:48 UTC, ring630 commented
@gkorompi #515