FEAT: edb.configuration.export operations
ansys/pyedb pull request #547
Opened 2024-06-07 10:34 UTC by ring630

2024-06-07 11:35 UTC, svandenb-dev approved these changes
LGTM

2024-06-07 13:26 UTC, svandenb-dev approved these changes
LGTM

2024-06-08 08:54 UTC, SMoraisAnsys requested changes
I request minor changes, LGTM otherwise !

2024-06-08 08:54 UTC, SMoraisAnsys commented on src/pyedb/configuration/cfg_operations.py
> +        self.keep_lines_as_path = kwargs.get("keep_lines_as_path", None)
```suggestion
        self.signal_list = kwargs.get("signal_list")
        self.reference_list = kwargs.get("reference_list")
        self.extent_type = kwargs.get("extent_type")
        self.expansion_size = kwargs.get("expansion_size")
        self.use_round_corner = kwargs.get("use_round_corner")
        self.output_aedb_path = kwargs.get("output_aedb_path")
        self.open_cutout_at_end = kwargs.get("open_cutout_at_end")
        self.use_pyaedt_cutout = kwargs.get("use_pyaedt_cutout")
        self.number_of_threads = kwargs.get("number_of_threads")
        self.use_pyaedt_extent_computing = kwargs.get("use_pyaedt_extent_computing")
        self.extent_defeature = kwargs.get("extent_defeature")
        self.remove_single_pin_components = kwargs.get("remove_single_pin_components")
        self.custom_extent = kwargs.get("custom_extent")
        self.custom_extent_units = kwargs.get("custom_extent_units")
        self.include_partial_instances = kwargs.get("include_partial_instances")
        self.keep_voids = kwargs.get("keep_voids")
        self.check_terminals = kwargs.get("check_terminals")
        self.include_pingroups = kwargs.get("include_pingroups")
        self.expansion_factor = kwargs.get("expansion_factor")
        self.maximum_iterations = kwargs.get("maximum_iterations")
        self.preserve_components_with_model = kwargs.get("preserve_components_with_model")
        self.simple_pad_check = kwargs.get("simple_pad_check")
        self.keep_lines_as_path = kwargs.get("keep_lines_as_path")
```
Dictionnary `get` command returns `None` by default. No need to specify it.

2024-06-09 22:19 UTC, SMoraisAnsys approved these changes

2024-06-10 07:15 UTC, merged