FEAT: EDB Configuration support in SIwave
ansys/pyedb pull request #709
Opened 2024-08-05 12:34 UTC by ring630

2024-08-06 08:32 UTC, ring630 commented
CI failure due to bug https://github.com/actions/upload-artifact/issues/591

2024-08-06 09:40 UTC, SMoraisAnsys commented
Updating the branch after main fix

2024-08-06 14:23 UTC, SMoraisAnsys requested changes
I left minor changes (refactoring and fixing typo)

2024-08-06 14:23 UTC, SMoraisAnsys commented on src/pyedb/siwave.py
> +    return True
```suggestion
    while True:
        if os.path.exists(folder_path):
            for root, _, files in os.walk(folder_path):
                if any(os.path.getsize(os.path.join(root, file)) > 0 for file in files):
                    return True
        
        # Wait before checking again.
        time.sleep(time_sleep)
```

2024-08-06 14:23 UTC, SMoraisAnsys commented on src/pyedb/siwave.py
> +            raise f"Failed to export EDB to {file_path}."
```suggestion
            raise RuntimeError(f"Failed to export EDB to {file_path}.")
```

2024-08-06 14:23 UTC, SMoraisAnsys commented on src/pyedb/siwave.py
> +            raise f"Failed to export EDB to {file_path}."
```suggestion
            raise RuntimeError(f"Failed to import EDB to {file_path}.")
```

2024-08-07 08:53 UTC, ring630 commented
@SMoraisAnsys thanks for the comments

2024-08-07 12:00 UTC, SMoraisAnsys approved these changes
LGTM

2024-08-07 12:01 UTC, merged