REFACTOR: EDB configuration example for DCIR setup
ansys/pyedb pull request #917
Opened 2024-11-28 14:55 UTC by gkorompi

2024-11-28 15:04 UTC, hui-zhou-a reviewed
Please wait until https://github.com/ansys/pyedb/pull/903 is merged. Then, merge main into this branch.

There are two more thing need  to be done to make this example show up in documentation.

update doc/source/conf.py and exmaples/use_configuration/index.rst

2024-12-01 19:04 UTC, SMoraisAnsys requested changes
As Hui mentionned, you should also update how this file interacts with the configuration by modifying RST files and also `conf.py` if required you want to add a thumbnail manually.

2024-12-01 19:04 UTC, SMoraisAnsys commented on examples/use_configuration/dcir.py
> +# -
```suggestion
# +
import json
import os
import tempfile

from ansys.aedt.core import Hfss3dLayout
from ansys.aedt.core.downloads import download_file

from pyedb import Edb

AEDT_VERSION = "2024.2"
NG_MODE = False

# -
```

2024-12-07 08:01 UTC, SMoraisAnsys commented on examples/use_configuration/dcir.py
> +# -
```suggestion
# -
```

2024-12-09 10:51 UTC, SMoraisAnsys approved these changes
LGTM

2024-12-09 10:52 UTC, SMoraisAnsys commented
@hui-zhou-a Can you have a look at this PR now that #903 is merged ?

2024-12-09 12:01 UTC, hui-zhou-a approved these changes
LGTM

2024-12-09 12:01 UTC, merged